name: windows_networking
description: Provides access to WinRT APIs from the Windows.Networking
  namespace using FFI.
version: 0.2.0
repository: https://github.com/halildurmus/dartwinrt/tree/main/packages/windows_networking
issue_tracker: https://github.com/halildurmus/dartwinrt/issues?q=is%3Aopen+is%3Aissue+label%3A%22pkg%3A+windows_networking%22

topics:
  - winrt
  - windows
  - ffi

environment:
  sdk: '^3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.0.1
  win32: ^5.0.0
  windows_foundation: ^0.2.0
  windows_storage: ^0.2.0

dev_dependencies:
  test: ^1.24.1
