name: windows_foundation
description: Provides access to WinRT APIs from the Windows.Foundation
  namespace using FFI.
version: 0.2.0
repository: https://github.com/halildurmus/dartwinrt/tree/main/packages/windows_foundation
issue_tracker: https://github.com/halildurmus/dartwinrt/issues?q=is%3Aopen+is%3Aissue+label%3A%22pkg%3A+windows_foundation%22

topics:
  - winrt
  - windows
  - ffi

environment:
  sdk: '^3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.1.0
  win32: ^5.0.6
  win32_registry: ^1.1.1
  windows_data: ^0.2.0
  windows_devices: ^0.2.0
  windows_graphics: ^0.2.0
  windows_media: ^0.2.0
  windows_networking: ^0.2.0
  windows_perception: ^0.1.0
  windows_services: ^0.1.0
  windows_storage: ^0.2.0
  windows_ui: ^0.2.0

dev_dependencies:
  test: ^1.24.1
