name: '🐛 Bug Report'
description: Create a report to help us improve
labels: ['type: bug', 'state: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this.
      options:
        - label: I have searched the
            [existing issues](https://github.com/dart-windows/dartwinrt/issues)
          required: true

  - type: dropdown
    id: packages
    attributes:
      label: On which packages did you experience this issue?
      description: You may select more than one.
      multiple: true
      options:
        - windows_ai
        - windows_applicationmodel
        - windows_data
        - windows_devices
        - windows_foundation
        - windows_gaming
        - windows_globalization
        - windows_graphics
        - windows_management
        - windows_media
        - windows_networking
        - windows_perception
        - windows_security
        - windows_services
        - windows_storage
        - windows_system
        - windows_ui
        - windows_web
        - winrtgen
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: What version are you using?
      description: Please specify the package names and versions
      placeholder: package - version
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: Description of the bug and what was expected.
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: How do you trigger this bug? Please walk us through it step
        by step.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        ...
      render: bash
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Supporting info to reproduce
      description: Please add any relevant code, screenshots and info needed to
        reproduce this issue.

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: Shell

  - type: textarea
    id: flutter-analyze
    attributes:
      label: Flutter analyze output
      description: Paste the output of `flutter analyze` here.
      placeholder: If there are any analysis errors, try resolving them before
        filing this issue.
      render: Shell

  - type: textarea
    id: flutter-doctor
    attributes:
      label: Flutter doctor output
      description: Paste the output of `flutter doctor -v` here.
      render: Shell
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/dart-windows/dartwinrt/tree/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
