name: windows_globalization
description: Provides access to WinRT APIs from the Windows.Globalization
  namespace using FFI.
version: 0.1.0+1
repository: https://github.com/halildurmus/dartwinrt/tree/main/packages/windows_globalization
issue_tracker: https://github.com/halildurmus/dartwinrt/issues?q=is%3Aopen+is%3Aissue+label%3A%22pkg%3A+windows_globalization%22

topics:
  - winrt
  - windows
  - ffi

environment:
  sdk: '^3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.0.1
  win32: ^5.0.0
  windows_foundation: ^0.2.0

dev_dependencies:
  test: ^1.24.1
